version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achat_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  
  app-foyer:
    depends_on:
      - mysqldb
    image: tp-foyer:latest  # The image of your Spring Boot app, built previously
    restart: on-failure
    ports:
      - "8085:8080"  # Exposing port 8080 of the Spring Boot app to 8085 on the host machine
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achat_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
